;; This file is maintained by Juju.
;;
;; Edits may be made in place, but will be overwritten next
;; time the charm is upgraded. If you make edits in place,
;; make sure they are synced back to the above branch.
;;
;; We run pgbouncer with identical configuration on both master
;; and standbys and both production and staging. After failover or
;; switchover, the hardcoded DNS names will need to be changed
;; to match.
;;
;; Both staging and production aliases are listed here so this
;; configuration can be shared between both staging and production
;; deploys. Unless misconfigured, production pgbouncer will fail
;; to connect to staging databases and vice versa due to firewall
;; rules.


;; database name = connect string
;;
;; connect string params:
;;   dbname= host= port= user= password=
;;   client_encoding= datestyle= timezone=
;;   pool_size= connect_query=

[databases]
;
;; production
;;
;; 10.22.112.20 == leyak (postgresql/1, hot standby)
;; 10.22.112.21 == gana (postgresql/2, current master)
;; 10.22.112.33 == pegasus (postgresql/3, hot standby)
;; 91.189.89.138 == zubeneshamali (previous PostgreSQL 9.1 server)

;; software_center_agent_production is being split into sca_snap_production
;; and sca_click_production.
;;
;; software_center_agent_production is the pre-migration name, and will
;; only exist on zubeneshamali
;; software_center_agent_production = host=zubeneshamali.canonical.com port=5432 dbname=software_center_agent_production

;; Pre-migration, clients will be configured to use these aliases to
;; talk to the existing database on zubeneshamali
;; During migration, this configuration will be altered to match the
;; _95
sca_snap_production = host=gana.internal port=5432 dbname=sca_snap_production
sca_click_production = host=gana.internal port=5432 dbname=sca_click_production
sca_snap_production_standby = host=pegasus.internal port=5432 dbname=sca_snap_production
sca_click_production_standby = host=pegasus.internal port=5432 dbname=sca_click_production


;; snapfind service databases
snapfind_snap_production = host=gana.internal port=5432 dbname=snapfind_snap_production
snapfind_curated_production = host=gana.internal port=5432 dbname=snapfind_curated_production
snapfind_snap_production_standby = host=pegasus.internal port=5432 dbname=snapfind_snap_production
snapfind_curated_production_standby = host=pegasus.internal port=5432 dbname=snapfind_curated_production

;; snapident service database
snapident_production = host=gana.internal port=5432 dbname=snapident_production pool_size=300
snapident_production_standby = host=pegasus.internal port=5432 dbname=snapident_production pool_size=300

;; snaprevs service database
snaprevs_production = host=gana.internal port=5432 dbname=snaprevs_production pool_size=300
snaprevs_production_standby = host=pegasus.internal port=5432 dbname=snaprevs_production pool_size=300

;; snapauth service database
snapauth_production = host=gana.internal port=5432 dbname=snapauth_production
snapauth_production_standby = host=pegasus.internal port=5432 dbname=snapauth_production

;; snapassert service database
snapassert_production = host=gana.internal port=5432 dbname=snapassert_production
snapassert_production_standby = host=pegasus.internal port=5432 dbname=snapassert_production

;; snapdelta service database RT#110763
snapdelta_production = host=gana.internal port=5432 dbname=snapdelta_production
snapdelta_production_standby = host=pegasus.internal port=5432 dbname=snapdelta_production

;; updown service database RT#109366
updown_production = host=gana.internal port=5432 dbname=updown_production
updown_production_standby = host=pegasus.internal port=5432 dbname=updown_production

;; packagereview service database, cRT#124905
packagereview_production = host=gana.internal port=5432 dbname=packagereview_production
packagereview_production_standby = host=pegasus.internal port=5432 dbname=packagereview_production

;; snapmodels service database, cRT#127707
snapmodels_production = host=gana.internal port=5432 dbname=snapmodels_production
snapmodels_production_standby = host=pegasus.internal port=5432 dbname=snapmodels_production

;; charmlibs service database, cRT#128425
charmlibs_production = host=gana.internal port=5432 dbname=charmlibs_production
charmlibs_production_standby = host=pegasus.internal port=5432 dbname=charmlibs_production

;; This database contains purchase and credit card details.
;; It cannot be migrated to sca-db as it requires encrypted disk,
;; and cohosting the db where other unrelated webapps could get
;; it is also probably a problem. It needs a separate home.
; payments_production = host=127.0.0.1 port=5432 dbname=payments_production

;; Legacy databases from zubeneshamali. These may also migrate
;; to the sca-db environment. Or maybe they will be dropped completely.
;
; awstrial_production = host=127.0.0.1 port=5432 dbname=awstrial_production
; libdep_production = host=127.0.0.1 port=5432 dbname=libdep_production
; production_myapps_library = host=127.0.0.1 port=5432 dbname=production_myapps_library
; reviews_production = host=127.0.0.1 port=5432 dbname=reviews_production
; ubuntu_recommender_production = host=127.0.0.1 port=5432 dbname=ubuntu_recommender_production
; usn_website_production = host=127.0.0.1 port=5432 dbname=usn_website_production
; uwc_production = host=127.0.0.1 port=5432 dbname=uwc_production


;; staging
;;
;; 10.22.112.16 == tennin (postgresql/0, current master)
;; 10.22.112.11 == adlet (postgresql/1, hot standby)
;;
;; software_center_agent_staging = host=tennin.internal port=5432 dbname=software_center_agent_staging
sca_snap_staging = host=tennin.internal port=5432 dbname=sca_snap_staging
sca_click_staging = host=tennin.internal port=5432 dbname=sca_click_staging
sca_snap_staging_standby = host=adlet.internal port=5432 dbname=sca_snap_staging
sca_click_staging_standby = host=adlet.internal port=5432 dbname=sca_click_staging

snapfind_snap_staging = host=tennin.internal port=5432 dbname=snapfind_snap_staging
snapfind_curated_staging = host=tennin.internal port=5432 dbname=snapfind_curated_staging
snapfind_snap_staging_standby = host=adlet.internal port=5432 dbname=snapfind_snap_staging
snapfind_curated_staging_standby = host=adlet.internal port=5432 dbname=snapfind_curated_staging
snapident_staging = host=tennin.internal port=5432 dbname=snapident_staging
snapident_staging_standby = host=adlet.internal port=5432 dbname=snapident_staging
snaprevs_staging = host=tennin.internal port=5432 dbname=snaprevs_staging
snaprevs_staging_standby = host=adlet.internal port=5432 dbname=snaprevs_staging
snapauth_staging = host=tennin.internal port=5432 dbname=snapauth_staging
snapauth_staging_standby = host=adlet.internal port=5432 dbname=snapauth_staging
snapassert_staging = host=tennin.internal port=5432 dbname=snapassert_staging
snapassert_staging_standby = host=adlet.internal port=5432 dbname=snapassert_staging

;; snapdelta service staging database RT#110763
snapdelta_staging = host=tennin.internal port=5432 dbname=snapdelta_staging
snapdelta_staging_standby = host=adlet.internal port=5432 dbname=snapdelta_staging

;; updown service staging database RT#109366
updown_staging = host=tennin.internal port=5432 dbname=updown_staging
updown_staging_standby = host=adlet.internal port=5432 dbname=updown_staging

;; packagereview service database, cRT#124905
packagereview_staging = host=tennin.internal port=5432 dbname=packagereview_staging
packagereview_staging_standby = host=adlet.internal port=5432 dbname=packagereview_staging

;; snapmodels service database, cRT#127707
snapmodels_staging = host=tennin.internal port=5432 dbname=snapmodels_staging
snapmodels_staging_standby = host=adlet.internal port=5432 dbname=snapmodels_staging

;; charmlibs service database, cRT#128425
charmlibs_staging = host=tennin.internal port=5432 dbname=charmlibs_staging
charmlibs_staging_standby = host=adlet.internal port=5432 dbname=charmlibs_staging

[pgbouncer]

logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid

listen_addr = *
listen_port = 5434

; unix socket is also used for -R.
; On debian it should be /var/run/postgresql
;unix_socket_dir = /tmp
;unix_socket_mode = 0777
;unix_socket_group =
unix_socket_dir = /var/run/postgresql

;;;
;;; Authentication settings
;;;

; any, trust, plain, crypt, md5
auth_type = md5
;auth_file = /8.0/main/global/pg_auth
auth_file = /etc/pgbouncer/userlist.txt

; comma-separated list of users, who are allowed to change settings
admin_users = pgbouncer,canonicaladmin

; comma-separated list of users who are just allowed to use SHOW command
stats_users = nagios

;;;
;;; Pooler personality questions
;;;

; When server connection is released back to pool:
;   session      - after client disconnects
;   transaction  - after transaction finishes
;   statement    - after statement finishes

; pool_mode transaction assumes we don't use certain features of PG
; See https://wiki.canonical.com/UbuntuOne/OperationsPlus/PoolingDBConnections#SQL feature map for pooling modes
; This can now be overridden per database.
pool_mode = transaction

;
; Query for cleaning connection immediately after releasing from client.
; No need to put ROLLBACK here, pgbouncer does not reuse connections
; where transaction is left open.
;
; Query for 8.3+:
;   DISCARD ALL;
;
; Older versions:
;   RESET ALL; SET SESSION AUTHORIZATION DEFAULT
;
; Empty if transaction pooling is in use.
;
server_reset_query = DISCARD ALL

;
; Comma-separated list of parameters to ignore when given
; in startup packet.  Newer JDBC versions require the
; extra_float_digits here.
;
ignore_startup_parameters = application_name,extra_float_digits

;
; When taking idle server into use, this query is ran first.
;   SELECT 1
;
server_check_query = select 1

; If server was used more recently that this many seconds ago,
; skip the check query.  Value 0 may or may not run in immediately.
server_check_delay = 30

;;;
;;; Connection limits
;;;

; total number of clients that can connect
max_client_conn = 3000

; default pool size.  20 is good number when transaction pooling
; is in use, in session pooling it needs to be the number of
; max clients you want to handle at any moment
default_pool_size = 50

; how many additional connection to allow in case of trouble
reserve_pool_size = 0

; if a clients needs to wait more than this many seconds, use reserve pool
reserve_pool_timeout = 1

; log if client connects or server connection is made
;log_connections = 1

; log if and why connection was closed
;log_disconnections = 1

; log error messages pooler sends to clients
;log_pooler_errors = 1


; If off, then server connections are reused in LIFO manner
;server_round_robin = 0

;;;
;;; Timeouts
;;;

;; Close server connection if its been connected longer.
server_lifetime = 3600

;; Close server connection if its not been used in this time.
;; Allows to clean unnecessary connections from pool after peak.
server_idle_timeout = 600

;; Cancel connection attempt if server does not answer takes longer.
server_connect_timeout = 15

;; If server login failed (server_connect_timeout or auth failure)
;; then wait this many second.
server_login_retry = 15

;; Dangerous.  Server connection is closed if query does not return
;; in this time.  Should be used to survive network problems,
;; _not_ as statement_timeout. (default: 0)
;query_timeout = 0

;; Dangerous.  Client connection is closed if the query is not assigned
;; to a server in this time.  Should be used to limit the number of queued
;; queries in case of a database or network failure. (default: 0)
;query_wait_timeout = 0

;; Dangerous.  Client connection is closed if no activity in this time.
;; Should be used to survive network problems. (default: 0)
client_idle_timeout = 0

;; Disconnect clients who have not managed to log in after connecting
;; in this many seconds.
client_login_timeout = 60

;; Disconnect clients idling inside a transaction for this long. This
;; is required to stop misbehaving clients victimizing other clients.
idle_transaction_timeout = 90

;; Clean automatically created database entries (via "*") if they
;; stay unused in this many seconds.
; autodb_idle_timeout = 3600

;;;
;;; Low-level tuning options
;;;

;; buffer for streaming packets
;pkt_buf = 2048

;; man 2 listen
;listen_backlog = 128

;; networking options, for info: man 7 tcp

;; Linux: notify program about new connection only if there
;; is also data received.  (Seconds to wait.)
;; On Linux the default is 45, on other OS'es 0.
;tcp_defer_accept = 0

;; In-kernel buffer size (Linux default: 4096)
;tcp_socket_buffer = 0

;; whether tcp keepalive should be turned on (0/1)
;tcp_keepalive = 1

;; following options are Linux-specific.
;; they also require tcp_keepalive=1

;; count of keepaliva packets
;tcp_keepcnt = 0

;; how long the connection can be idle,
;; before sending keepalive packets
;tcp_keepidle = 0

;; The time between individual keepalive probes.
;tcp_keepintvl = 0

;; DNS lookup caching time
;dns_max_ttl = 15

;; DNS zone SOA lookup period
;dns_zone_check_period = 0

